name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Next.js
        env:
          NEXT_PUBLIC_API_URL: https://my-healthcareai.onrender.com
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        run: |
          npm run deploy
